const COMPARE = {
  trainingpeaks: {
    title: "TrainingPeaks",
    icon: "📊",
    tagline: "Analitik ve koç pazaryeri — sen izlersin, koç yazar.",
    summary: "TrainingPeaks dayanıklılık sporcularının altın standardı analitik platformudur. TSS, CTL, ATL ve detaylı grafikler sunar; birçok koç planı buradan yönetir. Ancak plan güncellemesi genelde reaktiftir — veri değişince sen veya koçun müdahale etmelisin.",
    theirStrength: [
      "Derin analitik ve sezon planlama (ATP)",
      "Geniş koç ekosistemi ve pazaryeri",
      "TSS / güç / nabız bazlı detaylı raporlama",
      "Yarış ve antrenman kütüphanesi",
    ],
    driftlineEdge: [
      "HRV veya tempo sapması görüldüğünde planı senden önce günceller",
      "WhatsApp üzerinden proaktif bildirim — dashboard'a girmen gerekmez",
      "Garmin + Strava + WHOOP + Oura tek akışta",
      "Koç ücreti olmadan günlük adaptasyon",
    ],
    rows: [
      ["Proaktif müdahale", "Manuel / koç bağımlı", "Otomatik"],
      ["Çoklu veri kaynağı", "Entegrasyonlar var", "Birleşik sinyal okuma"],
      ["İletişim", "Uygulama / e-posta", "WhatsApp, proaktif"],
      ["Analitik derinlik", "Çok yüksek", "Odak: aksiyon"],
      ["Öğrenme eğrisi", "Yüksek", "Düşük"],
    ],
    verdict: "TrainingPeaks analiz ve koçluk altyapısı isteyenler için ideal. Driftline, veriyi okuyup planı kendisi değiştiren proaktif bir katman arayanlar için.",
  },
  "garmin-coach": {
    title: "Garmin Coach",
    icon: "⌚",
    tagline: "Garmin cihazına dahil — temel adaptif koşu planları.",
    summary: "Garmin Coach ücretsiz ve Garmin ekosistemine gömülü. Hedef mesafeye göre koşu planı oluşturur ve tamamladıkça adapte olur. Bisiklet ve yüzme kapsamı sınırlı; HRV veya uyku gibi çapraz sinyalleri derinlemesine kullanmaz.",
    theirStrength: [
      "Garmin saat ile ücretsiz",
      "Kurulumu kolay, koşuya odaklı",
      "Antrenmanları doğrudan saate gönderir",
      "Temel adaptasyon (seans tamamlama)",
    ],
    driftlineEdge: [
      "Triatlon ve çoklu spor desteği",
      "WHOOP / Oura HRV ve uyku sinyalleri",
      "Tempo kayması ve yüklenme oranı izleme",
      "Sapmada WhatsApp ile proaktif müdahale",
    ],
    rows: [
      ["Spor kapsamı", "Ağırlıklı koşu", "Koşu + bisiklet + triatlon"],
      ["Veri kaynakları", "Garmin", "Garmin, Strava, WHOOP, Oura"],
      ["Proaktiflik", "Plan tamamlama bazlı", "HRV, tempo, uyku tetiklemeli"],
      ["İletişim", "Garmin Connect", "WhatsApp"],
      ["Fiyat", "Ücretsiz (cihazla)", "€25/ay"],
    ],
    verdict: "Garmin Coach başlangıç koşu planı için yeterli ve ücretsiz. Driftline, ciddi dayanıklılık antrenmanı yapan ve çoklu sinyal isteyenler için.",
  },
  "whoop-coach": {
    title: "WHOOP Coach",
    icon: "💚",
    tagline: "Toparlanma odaklı AI — strain ve recovery skorları.",
    summary: "WHOOP Coach, WHOOP bandının recovery ve strain verisine dayalı öneriler sunar. Uyku ve HRV takibi güçlüdür. Antrenman planı yazma ve çoklu platform entegrasyonu sınırlıdır — öncelik toparlanma tavsiyesi.",
    theirStrength: [
      "24/7 recovery ve strain takibi",
      "Uyku analizi endüstri lideri",
      "WHOOP Coach AI sohbet",
      "Takım ve sosyal özellikler",
    ],
    driftlineEdge: [
      "WHOOP verisini antrenman planına dönüştürür",
      "Garmin / Strava antrenman verisi + WHOOP birlikte",
      "Planı sadece önermez — yeniden yazar",
      "Yarış hazırlığı ve periodizasyon",
    ],
    rows: [
      ["Odak", "Recovery & strain", "Tam antrenman planı"],
      ["Plan yazma", "Sınırlı", "14 günlük dinamik plan"],
      ["Entegrasyon", "WHOOP ekosistemi", "WHOOP + Garmin + Strava + Oura"],
      ["Proaktiflik", "Skor bazlı tavsiye", "Plan değişikliği + bildirim"],
      ["Spor", "Genel", "Dayanıklılık odaklı"],
    ],
    verdict: "WHOOP recovery takibi için mükemmel. Driftline, WHOOP verisini gerçek antrenman kararlarına çevirmek isteyenler için tamamlayıcı veya alternatif.",
  },
  trainerroad: {
    title: "TrainerRoad",
    icon: "🚴",
    tagline: "Bisiklet güç antrenmanı — yapılandırılmış planlar ve AI FTP.",
    summary: "TrainerRoad bisikletçiler için en olgun platformlardan biri. Adaptive Training, sürtünme antrenmanları ve güç bazlı planlar sunar. Koşu ve yüzme kapsamı yok; triatletler için tek başına yeterli değil.",
    theirStrength: [
      "Bisiklet güç antrenmanında derin uzmanlık",
      "Adaptive Training (TSS bazlı)",
      "Geniş workout kütüphanesi",
      "Plan Builder ve yarış hazırlığı (cycling)",
    ],
    driftlineEdge: [
      "Triatlon — yüzme, bisiklet, koşu tek planda",
      "WHOOP / Oura ile toparlanma sinyali",
      "WhatsApp proaktif koçluk",
      "Koşu tempo kayması izleme",
    ],
    rows: [
      ["Spor", "Bisiklet", "Triatlon + koşu + bisiklet"],
      ["Adaptasyon", "Güç / TSS bazlı", "HRV + tempo + yüklenme"],
      ["İletişim", "Uygulama", "WhatsApp proaktif"],
      ["Bisiklet derinliği", "Çok yüksek", "Yeterli (çoklu spor öncelik)"],
      ["Fiyat", "~$20/ay", "€25/ay"],
    ],
    verdict: "TrainerRoad ciddi bisikletçiler için. Driftline, triatlet veya koşu+bisiklet kombinasyonu yapanlar için.",
  },
  runna: {
    title: "Runna",
    icon: "🏃",
    tagline: "Popüler koşu uygulaması — yarış planları ve güç antrenmanı.",
    summary: "Runna hızlı büyüyen bir koşu koçluk uygulaması. Yarı maraton ve maraton planları, gym seansları ve Garmin/Apple Watch entegrasyonu sunar. Planlar genelde statik şablona dayanır; günlük HRV bazlı proaktif değişiklik sınırlı.",
    theirStrength: [
      "Güçlü koşu planı kütüphanesi",
      "Gym / mobilite entegrasyonu",
      "Garmin ve Apple Watch sync",
      "Topluluk ve sosyal özellikler",
    ],
    driftlineEdge: [
      "HRV 3 gün düşünce planı otomatik hafifletir",
      "Triatlon ve bisiklet desteği",
      "WHOOP / Oura çapraz sinyal",
      "WhatsApp ile koç sana yazar",
    ],
    rows: [
      ["Spor", "Koşu (+ gym)", "Koşu + bisiklet + triatlon"],
      ["Adaptasyon", "Haftalık ilerleme", "Günlük sinyal bazlı"],
      ["Proaktiflik", "Hatırlatıcılar", "Plan yeniden yazma"],
      ["Toparlanma", "Dinlenme günleri", "HRV + uyku tetiklemeli"],
      ["Fiyat", "~$15–20/ay", "€25/ay"],
    ],
    verdict: "Runna yapılandırılmış koşu planı ve gym isteyenler için harika. Driftline, veriye duyarlı proaktif koçluk arayanlar için.",
  },
  "intervals-icu": {
    title: "Intervals.icu",
    icon: "📈",
    tagline: "Ücretsiz analitik — grafikler, fitness ve koç bağlantısı.",
    summary: "Intervals.icu güçlü ve ücretsiz bir analitik platform. Fitness, yorgunluk, form grafikleri ve antrenman planlama sunar. DIY kullanıcılar ve koçlar için mükemmel — ancak AI koçluk veya proaktif bildirim yok.",
    theirStrength: [
      "Ücretsiz, açık kaynak ruhu",
      "Fitness / fatigue / form grafikleri",
      "Koç-athlete bağlantısı",
      "Geniş entegrasyon (Strava, Garmin, Wahoo)",
    ],
    driftlineEdge: [
      "Analiz yerine aksiyon — plan otomatik değişir",
      "AI koç yorumu ve WhatsApp bildirimi",
      "Teknik bilgi gerektirmez",
      "Sinyal okuma ve müdahale bir arada",
    ],
    rows: [
      ["Tür", "Analitik araç", "AI koç"],
      ["Kullanıcı", "DIY / teknik", "Her seviye"],
      ["Proaktiflik", "Yok", "Var"],
      ["Fiyat", "Ücretsiz", "€25/ay"],
      ["Analitik", "Çok derin", "Aksiyon odaklı"],
    ],
    verdict: "Intervals.icu veri meraklıları ve koçlu DIY sporcular için. Driftline, analizi koçluğa dönüştürmek isteyenler için.",
  },
  "athletica-ai": {
    title: "Athletica.ai",
    icon: "🤖",
    tagline: "AI dayanıklılık koçluğu — bilim bazlı adaptasyon.",
    summary: "Athletica.ai Driftline'a en yakın rakiplerden biri. Bilim bazlı AI koçluk, triatlon ve dayanıklılık planları sunar. Güçlü adaptasyon motoru var; iletişim modeli ve proaktif bildirim yaklaşımı farklılaşır.",
    theirStrength: [
      "Bilim bazlı AI adaptasyon",
      "Triatlon ve dayanıklılık desteği",
      "Workout Library ve plan özelleştirme",
      "Intervals.icu entegrasyonu",
    ],
    driftlineEdge: [
      "WhatsApp üzerinden proaktif mesajlaşma",
      "Sapmada senden önce yazar — uygulamaya girmen gerekmez",
      "HRV + tempo kayması + uyku birleşik sinyal",
      "Türkçe arayüz ve yerel odak",
    ],
    rows: [
      ["AI koçluk", "Var", "Var"],
      ["İletişim", "Uygulama / web", "WhatsApp proaktif"],
      ["Adaptasyon", "Bilim bazlı", "Sinyal tetiklemeli"],
      ["Proaktiflik", "Plan güncelleme", "Plan + bildirim"],
      ["Dil", "İngilizce", "Türkçe"],
    ],
    verdict: "İkisi de AI dayanıklılık koçu. Driftline, proaktif WhatsApp koçluk ve Türkçe deneyim isteyenler için; Athletica güçlü İngilizce platform alternatifi.",
  },
  humango: {
    title: "Humango",
    icon: "🏊",
    tagline: "AI triatlon koçu — dijital ikiz ve yarış simülasyonu.",
    summary: "Humango triatlon odaklı AI koçluk sunar. Dijital ikiz, yarış simülasyonu ve güçlü periodizasyon özellikleri var. Kurulum ve öğrenme eğrisi daha karmaşık olabilir; fiyatlandırma üst segmentte.",
    theirStrength: [
      "Triatlon uzmanlığı",
      "Dijital ikiz ve yarış simülasyonu",
      "Detaylı periodizasyon",
      "Çoklu cihaz entegrasyonu",
    ],
    driftlineEdge: [
      "Basit kurulum — 2 dakikada bağlan",
      "Günlük proaktif WhatsApp koçluk",
      "Sinyal sapmasında anında müdahale",
      "Daha erişilebilir fiyat (€25/ay)",
    ],
    rows: [
      ["Odak", "Triatlon (derin)", "Dayanıklılık (geniş)"],
      ["Kurulum", "Detaylı profil", "Hızlı onboarding"],
      ["İletişim", "Uygulama", "WhatsApp"],
      ["Simülasyon", "Güçlü", "Pratik odak"],
      ["Fiyat", "Üst segment", "€25/ay"],
    ],
    verdict: "Humango ciddi triatletler için premium AI. Driftline, basit ve proaktif koçluk isteyen geniş dayanıklılık kitlesi için.",
  },
  "nxt-run": {
    title: "NXT RUN",
    icon: "⚡",
    tagline: "AI koşu koçu — kişiselleştirilmiş koşu planları.",
    summary: "NXT RUN yapay zeka destekli koşu koçluğu sunar. Kişiselleştirilmiş planlar ve adaptasyon vaat eder. Bisiklet ve triatlon kapsamı sınırlı; çoklu wearable entegrasyonu Driftline kadar geniş değil.",
    theirStrength: [
      "AI koşu planı kişiselleştirme",
      "Modern mobil deneyim",
      "Koşuya odaklı adaptasyon",
      "Hedef yarış planları",
    ],
    driftlineEdge: [
      "Triatlon ve bisiklet desteği",
      "Garmin + WHOOP + Oura birleşik okuma",
      "Proaktif WhatsApp — uygulama açmadan bildirim",
      "HRV ve tempo kayması izleme",
    ],
    rows: [
      ["Spor", "Koşu", "Koşu + bisiklet + triatlon"],
      ["Veri", "Koşu odaklı", "Çoklu platform"],
      ["Proaktiflik", "Uygulama içi", "WhatsApp"],
      ["AI", "Plan adaptasyonu", "Plan + sinyal müdahalesi"],
      ["Toparlanma", "Temel", "HRV + uyku derin"],
    ],
    verdict: "NXT RUN saf koşu AI koçluğu arayanlar için. Driftline, çoklu spor ve wearable entegrasyonu isteyenler için.",
  },
  chatgpt: {
    title: "ChatGPT",
    icon: "💬",
    tagline: "Genel amaçlı AI — antrenman tavsiyesi, gerçek veri yok.",
    summary: "ChatGPT antrenman planı yazabilir, soruları yanıtlayabilir. Ancak Garmin, Strava veya WHOOP verinize gerçek zamanlı erişimi yok. Her seferinde bağlamı sen vermelisin; sapma olduğunda otomatik müdahale etmez.",
    theirStrength: [
      "Anında genel tavsiye",
      "Ucuz veya ücretsiz katman",
      "Her konuda esnek sohbet",
      "Plan taslağı hızlı üretim",
    ],
    driftlineEdge: [
      "Gerçek antrenman verisine bağlı",
      "HRV düştüğünde otomatik plan değişikliği",
      "Hatırlatma gerektirmez — proaktif yazar",
      "Dayanıklılık sporuna özel sinyal okuma",
    ],
    rows: [
      ["Veri bağlantısı", "Yok", "Garmin, Strava, WHOOP, Oura"],
      ["Proaktiflik", "Yok", "Var"],
      ["Uzmanlık", "Genel AI", "Dayanıklılık odaklı"],
      ["Plan güncelleme", "Manuel prompt", "Otomatik"],
      ["Güvenilirlik", "Halüsinasyon riski", "Veri bazlı"],
    ],
    verdict: "ChatGPT hızlı tavsiye ve beyin fırtınası için. Driftline, gerçek veriye dayalı güvenilir koçluk için.",
  },
  "human-coach": {
    title: "Human Coach",
    icon: "🧑‍🏫",
    tagline: "İnsan koç — kişisel ilişki, sınırlı günlük takip.",
    summary: "İnsan koç derin uzmanlık, motivasyon ve kişisel ilişki sunar. Ancak günlük HRV, uyku ve tempo verini her gün okuyamaz; iletişim genelde haftalık check-in ile sınırlı. Maliyet €100–300+/ay.",
    theirStrength: [
      "Derin kişisel ilişki ve motivasyon",
      "Yarış ve sezon deneyimi",
      "Esnek, tamamen özelleştirilmiş plan",
      "Sakatlık ve özel durum yönetimi",
    ],
    driftlineEdge: [
      "7/24 veri izleme — HRV, tempo, uyku",
      "Sapmayı sen fark etmeden yakalar",
      "€25/ay — insan koçun onda biri",
      "İnsan koçunla birlikte de kullanılabilir",
    ],
    rows: [
      ["Günlük takip", "Haftalık check-in", "Sürekli veri izleme"],
      ["Proaktiflik", "Sporcu bildirir", "AI proaktif yazar"],
      ["Fiyat", "€100–300+/ay", "€25/ay"],
      ["İlişki", "İnsan bağı", "AI + WhatsApp"],
      ["Ölçek", "1:1", "7/24"],
    ],
    verdict: "İnsan koç premium deneyim ve elit yarış hazırlığı için. Driftline, günlük veri takibi veya insan koçunun yanında ikinci katman olarak.",
  },
};